version: '3.3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    restart: always
    env_file:
      - ./.env
    ports:
      - 3306:3306
  app:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env
    restart: always